from flask import Flask, render_template
app = Flask(__name__)


recipes = [
    {
        'name': 'Beans on Toast',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/beans-on-toast.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/weeknight-beans-on-toast'
    },
    {
        'name': 'Chicken Caeser Sandwiches',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/chicken-caesar-sandwich.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree', 'Grill'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source':'https://www.bonappetit.com/recipe/grilled-chicken-sandwich-with-mustard-mayo'
    },
    {
        'name': 'Chicken Escabeche',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/chicken-escabeche.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/chicken-escabeche'
    },
    {
        'name': 'Crispy Chickpea Salad',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/chickpea-salad.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Salad', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/chopped-dinner-salad-with-crispy-chickpeas'
    },
    {
        'name': 'Poached Cod in Tomato Curry',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/poached-cod-tomato-curry.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree', 'Fish', 'Light'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/cod-poached-in-tomato-curry'
    },
    {
        'name': 'Grilled Pork Tenderloin with Peach Sauce',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/pork-peach-mustard.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree', 'Grill'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/pork-tenderloin-with-peach-mustard-sauce'
    },
    {
        'name': 'Tomato Toast',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/tomato-toast.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree', 'Vegetarian', 'Light'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/tomato-toast-with-chives-and-sesame-seeds'
    },
    {
        'name': 'Za\'atar Chicken',
        'ingredients': [],
        'ingredients_subset': [],
        'directions': '',
        'photo': '/static/images/zaatar-chicken.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Entree'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/zaatar-chicken-with-garlicky-yogurt'
    },
    {
        'name': 'Sesame Ginger Salmon',
        'ingredients': ['1/2 lb salmon per person', 'asparagus', 'rice pilaf', 'sesame seeds (topper)', 'green onions (topper)'],
        'ingredients_subset': ['1/4 cup olive oil', '2 tablespoons soy sauce', '2 tablespoons rice vinegar', '2 tablespoons sesame oil', '2 tablespoons brown sugar', '2 cloves garlic', '1 tablespoon grated fresh ginger', '2 tablespoons honey', '1/2 lemon juice', '1/2 teaspoon Sriracha (optional)'],
        'directions': ['Preheat oven to 450 degrees F.','Make the rice.', 'Make the marinade and let salmon marinate for at least 30 min.', 'Bake salmon for 12-15 min.', 'Cook asparagus: heat olive oil over medium-high heat, add asparagus, salt, and pepper and cook until done.', 'Serve, topping with sesame seeds and green onions.'],
        'photo': '/static/images/sesame-ginger-salmon.jpg',
        'tags': ['Heather', 'Entree', 'Favorite', 'Easy'],
        'formatted_tags': '',
        'source_name':'Damn Delicious',
        'source': 'https://damndelicious.net/2013/11/13/sesame-ginger-salmon/'
    },
    {
        'name': 'Elote Bowl',
        'ingredients': ['3/4 cup red quinoa', '1 can chickpeas', '2 ears corn', '1 jalapeno','2 radishes', 'fresh cilantro', '1 lime', '2 tbsp yogurt', '2 tbsp mayo', '1/4 tsp cayenne pepper', 'parmesan cheese'],
        'ingredients_subset': [],
        'directions': ['Cook the quinoa with 1 1/4 cups water, simmer for 12-15 min.', 'Prep the vegetables: slice radishes, cut off corn kernels, mince jalapeño, chop cilantro.', 'Make elote sauce: mix yogurt, mayo, 1/2 lime juice, salt.', 'Crisp chickpeas and corn: heat oil over high heat, cook chickpeas and corn ~4-6 min until crisp & lightly charred in spots. If this doesn\'t work, crisp separately.', 'Serve in 2 bowls, top with sauce, radishes, cilantro, parmesan, remaining lime juice, and cayenne pepper.'],
        'photo': '/static/images/elote-bowl.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Bowl', 'Vegetarian', 'Mexican'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/elote-bowl.jpg'
    },
    {
        'name': 'Take-out Style Noodles',
        'ingredients': ['8 oz asparagus', '2 tbsp fresh ginger', '4 radishes', '2 tbsp sesame oil', '2 tbsp tamari', '1 tbsp rice vinegar', '1 tbsp peanut butter', '2 tbsp chili garlic sauce', '11 oz fresh ramen noodles', '1/4 cup crispy shallots', '1/4 cup peanuts'],
        'ingredients_subset': [],
        'directions': ['Boil water for the ramen.', 'Prep: cut asaparagus into 1-inch pieces, mince ginger, grate radishes on wide setting.', 'Make the sauce: whisk ginger, sesame oil, tamari, rice vinegar, peanut butter, and chii garlic sauce.', 'Cook ramen noodles: 1-2 min, drain and rinse with cold water.', 'Stir fry: heat oil over medium-high heat, cook asapagus 2-3 min, add noodles, sauce, and salt, cook 2-3 more min.', 'Serve in 2 bowls and top with radishes, shallots, and peanuts.'],
        'photo': '/static/images/take-out-style-noodles.jpg',
        'tags': ['Heather', 'Entree', 'Vegetarian', 'Asian', 'Favorite'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/take-out-style-noodles.jpg'
    },
    {
        'name': 'Canh Chua Vietnamese Soup',
        'ingredients': ['1 shallot', '2 cloves garlic', '4 oz Swiss chard', '5 oz pineapple', '1 package Wildwood tofu', '1 Thai chile', '1 tbsp red miso paste', '2 tbsp tamari', '2 tsp tamarind paste', '5 oz rice noodles', '1 lime', 'fresh basil'],
        'ingredients_subset': [],
        'directions': ['Boil water for noodles.', 'Prep fruit and vegetables: mince garlic, chop Swiss chard stems and leaves, cut pineapple into bite sized pieces, drain tofu and cut into cubes, thinly slice Thai chile.', 'Fry the shallot: heat oil over medium-high heat, cook 3-5 min, remove and salt.', 'Make the broth: add oil to same pan, add garlic and red miso paste, cook 1 min. Add in tamari and tamarind. Add in 2 1/2 cups water and 1/4 tsp salt. Boil.', 'Cook the rice noodles: for 4-5 min, drain and rinse with cold water.', 'Once broth is boiling, add Swiss chard, pineapple, and tofu. Return to boil, lower heat, cook 2-3 min. Add 1/2 lime juice.', 'Serve in two bowls, top with lime wedges, basil, shallots, and chile.'],
        'photo': '/static/images/canh-chua-vietnamese-soup.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Soup', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/canh-chua-vietnamese-soup.jpg'
    },
    {
        'name': 'Fiesta Enchilada Skillet',
        'ingredients': ['1 onion', '2 cloves garlic', '4 oz kale', '1 ear corn', '1 can black beans', '1 can diced tomatoes', '2 tsp mole spice', '1 tsp cumin', '2 corn tortillas', '1/3 cup mozzarella', '1 avacado', '1 lime'],
        'ingredients_subset': [],
        'directions': ['Prepare the vegetables: dice onion, mince garlice, dice tomatoes, destem kale and roughly chop the leaves, cut kernels off, drain and rinse black beans.', 'Start the skillet: heat oil over medium-high heat, add onion, garlic, salt and pepper and cook for 3-5 min. Add kale, black beans, tomatoes, mole spice, cumin, salt, and cook for 4-6 min, stirring occasionally.', 'Crisp the tortillas: thinly slice the corn tortillas, heat oil over medium-high heat, add tortillas and cook for 2-3 min, remove and salt.', 'Finish the bake: broil the oven on low, stir corn kernels the bake and top with mozzerella, broil 3-4 min.', 'Top with sliced avacado and lime juice, serve with tortillas.'],
        'photo': '/static/images/fiesta-enchilada-skillet.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Mexican'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/fiesta-enchilada-skillet.jpg'
    },
    {
        'name': 'Thai Vegetable Stir-fry',
        'ingredients': ['1 cup jasmine rice', '1/4 cup cachews', '1 zucchini', '1 yellow squash', '2 mini sweet peppers', '1 peach', '5 cloves garlic', '5 Thai chiles', '2 tbsp tamari', '2 tbsp agave', '1 tbsp Worcestershire powder', '2 tbsp hemp seeds'],
        'ingredients_subset': [],
        'directions': ['Cook the rice with 1 1/4 cups water for 14-16 min.', 'Toast the cashews: heat oil over medium-high heat and cook for 4-6 min.', 'Prepare the vegetables: cut zucchini and squash into half-moons, thinly slice sweet peppers and peach, mince garlice, mince 2 Thai chili peppers.', 'Make the sauce: mix tamari, agave, and Worcestershire with a whisk.', 'Stir-fry: heat oil over medium heat, add zucchini, squash, and sweet peppers 3-5 min. Add Thai chiles and garlic and cook 30 seconds. Add sauce, peaches, and salt, and cook 2-3 min.', 'Stir in seeds and 1/2 cashews into rice, serve everything topped with remaining cashews.'],
        'photo': '/static/images/thai-vegetable-stir-fry.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/thai-vegetable-stir-fry.jpg'
    },
    {
        'name': 'Japanese Yam Sushi Bowl',
        'ingredients': ['2 Japanese yams', '3/4 cup quinoa speckled rice', '1 cucumber', '2 tsp rice vinegar', '2 tbsp sambal', '1 lime', '3 tbsp mayo', '4 oz baby spinach', '1 tbsp sesame seeds'],
        'ingredients_subset': [],
        'directions': ['Roast the yams: preheat oven to 400°F, cut yams into wedges, toss with oil, salt, and pepper, and bake 20-25 min.', 'Cook the rice: with 1 1/4 cups water for 15-20 min.', 'Marinate the cucumbers: thinly slice cucumbers and add to a bowl with rice vinegar and sambal.', 'Prepare the citrus aioli: add mayo, 1 tsp lime juice, and salt.', 'Sauté the spinach: heat oil over medium-high heat, add baby spinach, salt, and pepper and cook for 1-2 minutes.', 'Combine into bowls and serve, top with sesame seeds.'],
        'photo': '/static/images/japanese-yam-sushi-bowl.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Bowl', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/japanese-yam-sushi-bowl.jpg'
    },
    {
        'name': 'Vegan Mac and Cheese',
        'ingredients': ['1 onion', '2 cloves garlic', '2 tbsp vegan butter', '1 tbsp white miso paste', '1 tbsp flour', '3/4 cup almond flour', '6 oz shell pasta', '6 oz broccoli florets', '6 oz vegan cheddar cheese', '1/3 cup panko breadcrumbs', '1 scallion'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 400°F.', 'Boil water for the pasta. Chop onion and garlic.', 'Make the sauce: melt butter over medium-high heat, and add the onion, garlice, white miso paste, salt, and pepper. Cook, stirring frequently, until the miso paste dissolved and onion is translucent (~3-5min). Add flour and cook for 1 min, whisking constantly. Lower heat to medium and add almond milk, 1/4 cup at a time, while whisking. Simmer, continuing to whisk, until thick (~2-4 min).', 'Cook the pasta for 8-10 min.', 'Roast broccoli florets: add to baking sheet and toss with oilve oil, salt, and pepper. Roast for 6-8 min.', 'Blend: add sauce to a blender with cheddar cheese and salt and blend for 1 min.', 'Toast breadcrumbs: set oven to broil on high, pour cheese sauce over pasta in a baking dish and stir to combine, top with breadcrumbs, drive olive oil, salt, and pepper over top. Broil for 1-2 min.', 'Serve and top with scallions, broccoli on the side.'],
        'photo': '/static/images/vegan-mac-and-cheese.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/vegan-mac-and-cheese.jpg'
    },
    {
        'name': 'Bahn Mi Burgers',
        'ingredients': ['1/4 cup quinoa', '3 tbsp mayo', '2 Sriracha packets', '1 Persian cucumber', 'fresh cilantro', '4 oz broccoli slaw', '1 lime', '1 can chickpeas', '1/4 cup panko breadcrumbs', '2 ciabatta buns', '2 tbsp Korean black garlic seasoning', '1/4 cup pickled jalapeño'],
        'ingredients_subset': [],
        'directions': ['Cook the quinoa with 1/2 cup water for 8-10 min.', 'Make the aioli: mix mayo and Sriracha.', 'Make the slaw: mix cilantro leaves, broccoli slaw, and 1/2 lime juice.', 'Prepare burger mix: add cooked quinoa, 1/2 cup chickpeas, breadcrumbs, and salt to a food processor. Blend until well combined, ~10 pulses.', 'Toast the buns: set the oven on low broil, halve buns, toast for 3-5 min.', 'Cook burgers: form the burger mixture into 2 patties and gently press each side into Korean black garlic seasoning. Heat oil over medium-high heat and cook burgers about 3-5 min each side.', 'Serve burgers with aioli, sliced cucumber, 1/2 broccoli cilantro slaw, and jalapeño. Add chickpeas to 1/2 slaw and serve as a side.'],
        'photo': '/static/images/bahn-mi-burgers.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/bahn-mi-burgers.jpg'
    },
    {
        'name': 'Coconut Curry Udon Noodles',
        'ingredients': ['6 oz broccoli florets', '2 carrots', '1 shallot', '2 cloves garlic', '1 stalk lemongrass', '2 tbsp green curry paste', '1 can coconut milk', 'fresh cilantro', '1 lime', '6 oz udon noodles', '1/3 cup toasted coconut chips'],
        'ingredients_subset': [],
        'directions': ['Boil water for noodles.', 'Prepare vegetables: chop broccoli florets into bite-sized peices, thinly slice carrot diagonally, thinly slice shallot, mince garlice, cut lemongrass into pieces 2-3 inches long and press down on them.', 'Cook: heat oil over high heat, add broccoli and carrots and cook for 2-3 min. Reduce heat to low, add oil, shallot, garlic, and green curry paste and cook 1-2 min.', 'Simmer: add lemongrass, coconut milk, and 1/2 cup water. Bring to a boil then reduce and simmer for 2-3 min.', 'Cook udon noodles in the water 3-5 min, drain and rinse with cold water. Add to skillet with 1/2 cilantro and 1/2 lime.', 'Remove and discard lemongrass, serve and garnish with 1/2 cilantro, coconut chips, and lime wedges.'], 
        'photo': '/static/images/coconut-curry-udon-noodles.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/coconut-curry-udon-noodles.jpg'
    },
    {
        'name': 'Butternut Squash Gnocchi',
        'ingredients': ['6 oz butternut squash', '4 oz broccoli rabe', 'fresh parsley', '2 tbsp butter', '1/4 cup hazelnuts', '1 package gnocchi', '2 tsp white balsamic vinegar', '1/4 cup dried cranberries'],
        'ingredients_subset': [],
        'directions': ['Boil water for gnocchi.', 'Prepare vegetables: roughly chop butternut squash into 1/2 inch pieces, cut broccoli rabe into 1 inch pieces, finely chop parsley.', 'Toast the nuts: heat oil over medium heat and cook 3-4 min.', 'Cook the vegetables: in same skillet, add squash, broccoli, salt, and pepper and cook 4-6 min.', 'Cook gnocchi for 3-4 min, save 1/3 cup pasta water. Add gnoccchi to skillet and cook 4-6 min. Add pasta water and white balsamic vinegar until mostly evaporated, ~1 min. Add cranberries, 1-2 min.', 'Serve, topping with hazelnuts and parsley.'],
        'photo': '/static/images/butternut-squash-gnocchi.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/butternut-squash-gnocchi.jpg'
    },
    {
        'name': 'Autumn Bibimbap',
        'ingredients': ['3/4 cups sushi rice', '6 oz rainbow carrots', '6 oz Brussels sprouts', '1 tbsp gochujang', '1 cucumber', '1 scallion', '1 clove garlic', '2 tbsp mayo', '2 tbsp sesame oil', '6 oz baby spinach', '1 tbsp sesame seeds', '4 oz kimchi'],
        'ingredients_subset': [],
        'directions': ['Preheat the oven to 400°F.', 'Cook the sushi rice in 1 1/4 cups water 15-18 min.', 'Prep vegetables: slice carrots, halve Brussels sprouts.', 'Roast vegetables: toss carrots in oil, toss Brussels sprouts in a glaze of gochujang and 1 tbsp water. Roast for 14-16 min.', 'Prepare toppings: thinly slice cucumbers and scallion. Mince garlic, add to mayo, salt, 2 tsp water, and 2 tsp sesame oil. Whisk sesame aioli.', 'Cook the spinach: heat 1 tsp sesame oil over medium-high heat, add spinach and cook 1-2 min.', 'Crisp the rice: fluff cooked rice, return skillet to medium-high heat and ad remaining sesame oil. Add rice, press into an even layer, and cook until bottom begins to crackle and brown, 5-7 min, don\'t stir.', 'Serve and top with aioli, scallion, and sesame seeds.'],
        'photo': '/static/images/autumn-bibimbap.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', "Asian"],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/autumn-bibimbap.jpg'
    },
    {
        'name': 'Tofu Halloumi',
        'ingredients': ['1 clove garlic', '2 tbsp red wine vinegar', '1 tbsp agave', '8 oz watermelon', 'fresh mint', '1 zucchini', '1 package Wildwood tofu', '2 tbsp zaatar', '2 tbsp nutritional yeast', '2 tbsp almonds'],
        'ingredients_subset': [],
        'directions': ['Prep marinade: mince garlic, add red wine vingar and agave. Whisk well to combine and gradually add 3 tbsp olive oil.', 'Marinate watermelon: slice watermelon, roughly chop mint, add to marinade with salt and coat the watermelon.', 'Prep Zucchini: cut into thirds and then slice into 1/2 inch planks the long way.', 'Prepare the halloumi: drain tofu and slice length-wise into 6 pieces. Combine zaatar, yeast, salt, and pepper and coat the tofu.', 'Char the zucchini: heat a skillet over medium heat, toast almonds for 3-4 min, increase heat to high and add oil. Add sliced zucchini and cook 2-3 min, add salt and pepper.' , 'Sear the halloumi: return skillet to medium-high heat, add oil, add tofu, cook 3-4 min per side.', 'Serve topped with watermelon mint salad and toasted almonds.'],
        'photo': '/static/images/tofu-halloumi.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/tofu-halloumi.jpg'
    },
    {
        'name': 'Buffalo Cauliflower Salad',
        'ingredients': ['1/2 cup faro', '1/2 cup hot sauce', '3 tbsp butter', '1 tsp garlic powder', '6 oz cauliflower florets', '1 head green leaf lettuce', '4 oz heirloom cherry tomatoes', '1 carrot', '1 celery stalk', '1/4 cup ranch'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 425°F.', 'Cook farro with water 1 inch above farro, for 18-20 min.', 'Make sauce: combine hot sauce, butter, garlic powder, salt in saucepan over medium heat. Whisk until butter melted, remove from heat.', 'Bake cauliflower: cut cauliflower into bite-sized pieces, coat with buffalo sauce, bake 15-18 min. Reserve extra sauce.', 'Make salad: roughly chop lettuce, quarter tomatoes, shred carrot on thickest setting, slice celery. Toss with 1/2 ranch.', 'Serve and drizzle with remaining buffalo sauce and ranch.'],
        'photo': '/static/images/buffalo-cauliflower-salad.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Salad', 'Vegetarian', 'Mediterranean'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/buffalo-cauliflower-salad.jpg'
    },
    {
        'name': 'Eggplant Flatbreads',
        'ingredients': ['1 eggplant', '1/2 cup bulgur wheat', '1 celery stalk', '4 oz heirloom cherry tomoatoes', '1 shallot', 'fresh parsley', '2 tsp za\'atar', '2 tbsp + 2 tsp champagne vinegar', '3 tbsp tahini', '2 tbsp mango chutney', '2 whole wheat pitas'],
        'ingredients_subset': [],
        'directions': ['Make bulgur (boil 1 1/4 cups water, pour 3/4 cups into bowl with bulgur, cover and sit 18-20 min).', 'Prepare produce (dice celery, quarter tomoatoes, mince shallot, roughly chop parsley).', 'Broil eggplant (set oven to broil on high, cut eggplant into 1 inch thick rounds, place on baking sheet, add oil, za\'atar, and salt. Broil 5-8 min on each side).', 'Toss celery tabbouleh (add celery, tomatoes, shallot, and parsley to finished bulgar. Add 2 tbsp champagne vinegar, 2 tbsp olive oil, salt, and pepper).', 'Make the mango tahini amba (combine and stir remaining vinegar, tahini, mango chutney, and salt).' ,'Warm pitas in foil in oven, 2-4 min.', 'Serve with everything in the pita, with any extra tabbouleh and mango tahini amba on the side.'],
        'photo': '/static/images/eggplant-flatbreads.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/eggplant-flatbreads.jpg'
    },
    {
        'name': 'Sweet Potato Black Bean Tacos',
        'ingredients': ['1 sweet potato', '1 peach', '1/2 cup kimchi', '1 scallion', '1 can black beans', '1 lime', '1/4 cup mayo', '6 tortillas', '2 oz green cabbage', '1 lemon'],
        'ingredients_subset': [],
        'directions': ['Roast sweet potato: preheat oven to 450°F. Dice sweet potato (no need to peel), add to baking sheet with 2 tsp oil, salt, and pepper. Roast 10-15 min.', 'Mix the kimchi: thinly slice peach, roughly chop kimchi, combine.', 'Prep aioli: combine and mix lime zest, 1/2 lemon juice, mayo, and salt.', 'Cook black beans: heat skillet over medium-high heat, add black beans and 1/2 cup water, cook 2-3 min. Mash about half of them, cook 2-3 more min and salt.', 'Crisp tortillas in oil over medium-high heat.', 'Fill tacos with sweet potato and black beans, top with peach kimchi, sliced scallion, green cabbage, and aioli.'],
        'photo': '/static/images/sweet-potato-black-bean-tacos.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Mexican'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/sweet-potato-black-bean-tacos.jpg'
    },
    {
        'name': 'Jeweled Biryani',
        'ingredients': ['1/2 cup green lentils', '1/2 cup jasmine rice', '6 oz butternut squash', '2 tsp curry powder', '1 cucumber', '2 tsp lemon juice', '2 scallions', 'fresh mint', '1.5 oz dried apricots', '2 tsp coconut oil', '1/4 cup golden raisins', '1/4 cup cashews'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 425°F.', 'Cook lentis with 2 1/2 cups water for 12 min, add in jasmine rice and cook 10-12 more min.', 'Roast butternut squash: cube the squash, toss with curry powder, 2 tbsp oil, salt, and pepper, and spread on baking sheet. Roast 15-18 min.', 'Marinate cucumbers: thinly slice cucumbers and let sit in 1/2 lemon juice, 1 tsp olive oil, and salt.', 'Prep: thinly slice scallions, tear mint leaves, dice apricots.', 'Heat coconut oil over medium-low heat and cook apricots, raisins, and cashews for 3-4 min. Add finished rice & lentils to skillet, add 1/2 scallions, remaining lemon juice, and salt. Fold in squash.', 'Serve and top with mint and remaining scallions, with cucumbers on the side.'],
        'photo': '/static/images/jeweled-biryani.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/jeweled-biryani.jpg'
    },
    {
        'name': 'Five-spice Tofu Stir-fry',
        'ingredients': ['1 package tofu', '1/2 tsp Chinese five-spice', '2 cloves garlic', '1 red bell pepper', '6 oz bok choy', '1 tbsp gochujang', '2 tbsp apricot preserves', '6 oz soba noodles', '1 tbsp sesame oil', '1 tbsp sesame seeds'],
        'ingredients_subset': [],
        'directions': ['Boil water for noodles.', 'Drain, dry, and cut tofu into 1 inch cubes. Heat oil over medium-high heat, add tofu, Chinese five-spice, and salt. Cook 4-5 min.', 'Prep vegetables: mince garlic, slice red bell pepper, chop bok choy.', 'Make the sauce: whisk gochujang, apricot preserves, and 2 tbsp water.', 'Cook noodles for 4-5 min, drain, run under cold water, and toss with 1 tsp sesame oil.', 'Stir-fry: heat remaining sesame oil over medium-high heat, add bok choy, salt, pepper and cook 1-2 min. Add garlic, bell pepper, and sesame seeds, cook 1 min. Add tofu, chile-apricot sauce, cook 1-2 min.', 'Serve stir-fry on top of noodles.'],
        'photo': '/static/images/five-spice-tofu-stir-fry.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/five-spice-tofu-stir-fry.jpg'
    },
    {
        'name': 'Italian Cannellini Bean Stew',
        'ingredients': ['1 carrot', '1 onion', '1 celery stalk', '2 cloves garlic', '1 lemon', '6 oz sausage', '1 can cannellini beans', '1 tsp Herbs de Provence', '2 tbsp tomato paste', '2 packets vegetable broth concentrate', '4 oz mustard greens', '2 tsp parmesan'],
        'ingredients_subset': [],
        'directions': ['Prep vegetables: slice carrots into thin rounds, chop onion, chop celery, mince garlic, halve lemon.', 'Cook the sausage: slice into rounds, heat oil over medium-high heat in a big pot, cook 3-5 min.', 'Begin the stew: return pot to medium-high heat, add carrots, onions, celery, garlic, and cook 3-5 min. Add cannellini beans, Herbs de Provence, tomato paste, vegetable broth concentrate, and 2 cups water. Bring to a boil then reduce heat to a simmer.', 'Remove mustard green stems, chop leaves, add to pot and simmer 3-5 more min. Add 1/2 lemon juice. Season stew with salt and pepper and top with sausage, parmesan, and lemon wedges.'],
        'photo': '/static/images/italian-cannellini-bean-stew.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Soup', 'Italian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/italian-cannellini-bean-stew.jpg'
    },
    {
        'name': 'Black Bean Burgers',
        'ingredients': ['1 sweet potato', '1 can black beans', '1 can black beans', '1 clove garlic', '1 1/2 tsp cumin', '1 tbsp Worcestershire powder', '1 tbsp flaxseed meal', '2 tbsp garbanzo bean flour', '2 tsp Aleppo pepper flakes','2 tbsp mayo', '2 tsp ketchup', '2 buns', '2 oz pickles', '2 lettuce leaves'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 425°F.', 'Bake fries: cut sweet potato into wedges, transfer to baking sheet and toss with oil, salt, and pepper, bake for 18-22 min.', 'Blend the burger mix: add black beans, garlic, cumin, Worcestershire powder, flaxseed meal, garbanzo bean flour, Aleppo pepper flakes, and salt to a blender. Pulse a few times until combined, form into 2 patties and chill in fridge.', 'Mix the sauce: combine mayo, ketchup, and salt.', 'Sear the burgers: heat oil over medium-high heat, add burgers and cook 3-5 min each side.', 'Serve and top with pickles, lettuce, and sauce.'],
        'photo': '/static/images/black-bean-burgers.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/black-bean-burgers.jpg'
    },
    {
        'name': 'Nicoise Salad',
        'ingredients': ['3/4 cup French lentils', '8 oz new potatoes', '1 clove garlic', '6 oz green beens', '1 cucumber', '1 tbsp French mustard herb blend', '4 oz heirloom cherry tomatoes', '1 tbsp lemon juice', 'French tarragon', '2 oz baby spinach', '1/4 cup walnuts', '1/4 cup kalamata olives'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 425°F.', 'Prepare lentils with 2 cups water for 18-20 min, season with salt and pepper.', 'Boil 1 inch of water for green beans.', 'Prepare vegetables: quarter potatoes, thinly slice garlic and cucumber, trim green beans.', 'Roast potatoes: add to baking sheet and toss with French mustard herb blend, oil, salt, pepper, and roast for 18-22 min.', 'Steam green beans for 1 min in the boiling water, drain and rinse with cold water.', 'Cook tomatoes: heat oil over medium heat, add garlic and cook 30 seconds, add tomatoes and salt, cook 4-6 min.', 'Prepare vinaigrette: remove and roughly chop garlic and tomatoes, combine in a bowl with tarragon leaves, 1 tbsp olive oil, lemon juice, salt, and pepper.', 'Serve and top with walnuts and olives.'],
        'photo': '/static/images/nicoise-salad.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Salad', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/nicoise-salad.jpg'
    },
    {
        'name': 'Corn Crab Dumplings',
        'ingredients': ['1/2 cup black rice', '2 tsp fresh ginger', '3 scallions', '1 ear corn', '1/2 cup hearts of palm', '1 tbsp cream cheese', '1 1/2 tsp Old Bay Seasoning', '2 tsp Sriracha', '14 wonton wrappers', '1 tbsp sesame oil', '2 tsp tamari', '1/4 cup sweet chili sauce'],
        'ingredients_subset': [],
        'directions': ['Cook black rice with 1 cup water for 30-35 min.', 'Prepare produce: mince ginger, thinly slice scallions, cut off corn kernels, drain hearts of palm.', 'Make dumpling mix: combine cream cheese, Old Bay Seasoning, and Sriracha, 1/4 cup scallion, corn, and hearts of palm, and salt.', 'Fill the wonton wrappers with dumpling mix.', 'Sear the dumplings: heat oil over medium heat, add dumplings and cook until browned and crispy, 2-3 min. Flip and cook additional min. Add 1/3 cup water, reduce heat to medium, and cover. Steam 3-4 min.', 'Finish rice: wipe skillet, heat sesame oil over medium-high heat, add ginger and cook for 30 seconds. Add cooked rice, remaining scallions, tamari, and salt.', 'Cool 1-2 min. Serve with sweet chili sauce for dipping.'],
        'photo': '/static/images/corn-crab-dumplings.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/corn-crab-dumplings.jpg'
    },
    {
        'name': 'Tomato-braised Artichokes',
        'ingredients': ['3/4 cup quinoa', '1 shallot', '3 cloves garlic', '1/4 cup cured black olives', '8 oz artichoke hearts', '1 can crushed tomatoes', '1 cucumber', 'fresh dill', '1 tbsp lemon juice', '1 tbsp white vinegar', '1/4 cup mayo'],
        'ingredients_subset': [],
        'directions': ['Cook the quinoa with 1 1/4 cup water for 12-15 min.', 'Prepare vegetables: mince shallot and garlic, remove olive pits and roughly chop, drain artichokes.', 'Begin to braise: heat oil over medium-high heat, add shallot and garlic and cook for 1 min. Add artichokes, crushed tomatoes, 1 cup of water, bring to a boil and simmer until it thickens.', 'Prepare the sauce: grate cucumber on large setting into a bowl and mix with finely chopped dill, lemon juice, white vinegar, mayo, and salt.', 'Serve topped with cucumer dill sauce and olives.'],
        'photo': '/static/images/tomato-braised-artichokes.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/tomato-braised-artichokes.jpg'
    },
    {
        'name': 'Crispy Buckwheat Bowl',
        'ingredients': ['1 cup buckwheat groats', '6 oz broccolini', '4 radishes', '4 oz snap peas', '1 lemon', '1/2 cup black-eyed peas', '1/4 cup pecans', '1 scallion', '2 tbsp cilantro chutney'],
        'ingredients_subset': [],
        'directions': ['Cook the buckwheat in 2 cups of water for 8-10 min.', 'Prepare vegetables: trim broccolini stems, thinly slice radishes, cut snap peas in half diagonally.', 'Marinate vegetables: in a bowl combine radishes, snap peas, black-eyed peas, 1/2 lemon juice, 1 tbsp olive oil, salt, and pepper.', 'Prepare pesto: finely chop pecans, thinly slice scallion. In a bowl combine pecans, scallion, cilantro chutney, 2 tsp lemon juice, 1 tsp olive oil, and salt.', 'Crisp the buckwheat: heat oil over medium-high heat, add cooked buckwheat and cook 3-5 min, stir, cook 2 more min and season with salt and lemon. Add broccolini with 1/4 cup water and cook 3-5 min.', 'Serve bowls topped with marinated vegetables and cilantro pesto.'],
        'photo': '/static/images/crispy-buckwheat-bowl.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Lunch' 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/crispy-buckwheat-bowl.jpg'
    },
    {
        'name': 'Beef Bulgogi Bowl',
        'ingredients': ['1/2 cup jasmine rice', '2 scallions', '5 tsp white wine vinegar', '1 cucumber', '4 oz shredded carrots', '10 oz ground beef', '1 tbsp sesame seeds', '4 oz bulgogi sauce', '4 tbsp sour cream', '1 tsp sriracha' ],
        'ingredients_subset': [],
        'directions': ['Cook rice with 3/4 cup water for 15 min.', 'Thinly slice scallions, separating whites from greens.', 'Pickle cucumber: shave cucumber length-wise into thick ribbons, rotating until you get to the seedy core and then discard. Toss in a bowl with 1/2 vinegar, 1/2 tsp sugar, and salt. Drain before adding to bowls at the end.', 'Cook carrots: heat oil over medium-high heat, add shredded carrots, salt, and pepper and cook for 1 min.', 'Cook beef: heat more oil over medium-high heat, add scallion whites and cook 30 seconds. Add beef, salt, and pepper and cook 5-7 min. Add 1/2 sesame seeds and remaining vinegar, cook for 30 seconds. Add bulgogi sauce and bring to simmer, add more salt and pepper.', 'Make sriracha cream: in a bowl, combine sour cream, sriracha, salt, and 1 tsp of water at a time until mixture is a drizzlying consistency.', 'To rice, mix in 1 tbsp butter, salt, and pepper.', 'Combine everything into bowls, top with scallion greens and remaining sesame seeds.'],
        'photo': '/static/images/beef-bulgogi-bowls.jpg',
        'tags': ['Heather', 'Entree', 'Bowl', 'Asian',],
        'formatted_tags': '',
        'source_name':'Hello Fresh',
        'source': '/static/sources/beef-bulgogi-bowls.jpg'
    },
    {
        'name': 'Israeli Stuffed Peppers',
        'ingredients': ['3/4 cup saffron rice', '1 beef bouillon cube', '1 carrot', '1 onion', '3 cloves garlic', '2 Anaheim peppers', '1/4 cup almonds', '1 1/4 tsp Israeli spice blend', '2 tbsp dried cherries', '4 oz baby spinach'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 425°F.', 'Cook rice with 1 1/4 cups water for 15-20 min.', 'Prep: dissolve bouillon cube in 1/2 cup hot water, dice carrot and onion, thinly slice garlic, butterfly the peppers.', 'Make the filling: heat oil over medium-high heat, add carrot, onion, 1/2 garlic, salt, and cook 5-6 min. Increase heat to high, add oil and bouillon broth, cook 4-6 more min. Add almonds, Israeli spice blend, and dried cherries and cook 2-3 min.', 'Stuff the peppers and roast in oven 8-10 min.', 'Saute spinach: heat oil over high heat, add remaining garlic, baby spinach, salt, pepper, and cook 2-3 min.', 'Serve peppers over rice with spinach on side.'],
        'photo': '/static/images/israeli-stuffed-peppers.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/israeli-stuffed-peppers.jpg'
    },
    {
        'name': 'Watermelon Poke Bowls',
        'ingredients': ['3/4 cup sushi rice', '2 radishes', '1 cucumber', '1 oz macademia nuts', '2 tsp sesame oil', '2 tbsp tamari', '1 tbsp rice vinegar', '1 avacado', '7 oz watermelon'],
        'ingredients_subset': [],
        'directions': ['Cook rice with 1 1/4 cups water for 12-15 min, let stand for 5.', 'Prepare toppings: thinly slice radishes and cucumber, slice avacado, cut watermelon into small cubes, roughly chop macademia nuts.', 'Make dressing: whisk sesame oil, tamari, rice vinegar, salt, and pepper.', 'Serve in bowls.'],
        'photo': '/static/images/watermelon-poke-bowls.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Asian', 'Easy'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/watermelon-poke-bowls.jpg'
    },
    {
        'name': 'Chicken Sausage Spinach Ricotta Ravioli',
        'ingredients': ['2 scallions', '1 tomato', '1 lemon', '9 oz Italian sausage', '1 tbsp Italian seasoning', '9 oz spinach and ricotta ravioli', '1 package chicken stock concentrate', '4 tbsp sour cream'],
        'ingredients_subset': [],
        'directions': ['Boil water for pasta.', 'Prep: slice scallions, dice tomato, wedge lemon.', 'Cook sausage: heat oil over medium-high heat, add scallion whites, sausage, Italian seasoning, and cook for 3-5 min. Add tomato and cook 1-2 min, then turn off heat.', 'Cook ravioli for 4-5 min and reserve 1/2 cup water.', 'Turn sausage pan back on low heat and add stock concentrate, squeeze of lemon juice, splash of pasta water, and cook for 1-2 min. Add sour cream, 1 tbsp butter, salt, and pepper. Add more pasta water as needed until creamy consistency. Add ravioli, salt, pepper, and lemon juice.', 'Serve and top with scallion greens and lemon wedges.'],
        'photo': '/static/images/chicken-sausage-spinach-ricotta-ravioli.jpg',
        'tags': ['Heather', 'Entree'],
        'formatted_tags': '',
        'source_name':'Hello Fresh',
        'source': '/static/sources/chicken-sausage-spinach-ricotta-ravioli.jpg'
    },
    {
        'name': 'Creamy Miso Risotto',
        'ingredients': ['4 tsp concentrated vegetable broth', '1 onion', '1 clove garlic', '8 oz diced root vegetables', '3/4 cup arborio rice', '1 lemon', '1 scallion', '1 tbsp butter', '2 tbsp white miso paste', '1 tbsp sesame oil', '1/2 cup dry white wine (optional)'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 450°F.', 'In pot, simmer concentrated broth with 4 1/2 cups water.', 'Dice onion, mince garlic.', 'Roast vegetables: add diced vegetables to baking sheet with oil, salt, and pepper. Roast for 15-17 min.', 'Start risotto: in skillet, heat olive oil over medium heat with onion and garlic, cook until softened, ~3-5 min. Add rice and salt, cook 2-3 min. If using wine, add here.', 'Add the broth: add 1/2 cup of broth to the skillet and stir until bubbling liquid is almost evaporated. Continue until rice is tender, ~30-35 min.', 'Finish risotto: stir butter and white miso paste into skillet, add salt and pepper. Remove from heat and add lemon juice.', 'Serve: zest lemon and toss with roasted winter vegetables. Top risotto with vegetables and thinly sliced scallions, drizzle sesame oil. '],
        'photo': '/static/images/creamy-miso-risotto.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Entree', 'Vegetarian', 'Favorite'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/creamy-miso-risotto.jpg'
    },
    {
        'name': 'Spinach plum salad',
        'ingredients': ['spinach', '2 plums', '1 lemon'],
        'ingredients_subset': [],
        'directions': ['Roughly chop spinach and slice plums.', 'Mix and toss with 1 tbsp lemon juice, 2 tbsp olive oil, salt, and pepper. '],
        'photo': '/static/images/spinach-plum-salad.jpg',
        'tags': ['Heather', 'Purple Carrot', 'Salad', 'Small Plate'],
        'formatted_tags': '',
        'source_name':'Purple Carrot',
        'source': '/static/sources/spinach-plum-salad.jpg'
    },
    {
        'name': 'Spicy Garlic Shrimp',
        'ingredients': ['12 jumbo shrimp', '2 tbsp olive oil', '2 garlic cloves', '1/4 tsp red pepper flakes', '1 tsp McMcormick Montreal Steak Seasoning', '1 lemon', 'fresh parsley (optional)'],
        'ingredients_subset': [],
        'directions': ['Heat oil over medium-high heat and add garlic, red pepper flakes, and shrimp.', 'Cook ~3 min and toss with lemon zest and juice and parsley.'],
        'photo': '/static/images/spicy-garlic-shrimp.jpg',
        'tags': ['Heather', 'Small Plate', 'Seafood', 'Easy'],
        'formatted_tags': '',
        'source_name':'Online',
        'source': 'https://www.food.com/recipe/4-minute-spicy-garlic-shrimp-107997'
    },
    {
        'name': 'Vegan Tomato Kibbeh',
        'ingredients': ['1 1/2 cups fine bulgur', '5 sprigs fresh parsley', '2 sprigs frest mint', '2 tsp crushed dried mint', '1 sweet onion', '2 large tomatoes', '1/2 red bell pepper', '1/2 tsp cinnamon', '1/4 tsp cayanne pepper', '1 lemon'],
        'ingredients_subset': [],
        'directions': ['Prep: coursely chop onion, bell pepper, and tomatoes.', 'In a food processor, pulse the parsley and mint until they are finely chopped, but not pureed. Add the onion and continue pulsing until it is also finely chopped.', 'In a bowl, combine bulgur and mixture from food processor.', 'Pulse tomatoes and red bell pepper in the processor a few times until they are finely chopped but not liquid, then add to bowl.','Knead bowl mixtur, seasoning with salt, pepper, cinnamon, cayenne, crushed dried mint, lemon juice, and 1/2 cup olive oil.', 'Let rest 1 hr at room temp, then serve spread out about 1/2 inch thick and drizzle with more olive oil.'],
        'photo': '/static/images/vegan-tomato-kibbeh.jpg',
        'tags': ['Heather', 'Small Plate', 'Vegetarian', 'Easy'],
        'formatted_tags': '',
        'source_name':'Online',
        'source': 'https://www.splendidtable.org/recipes/vegan-tomato-kibbeh'
    },
    {
        'name': 'Greek Chicken Tabbouleh Salad',
        'ingredients': ['3 tbsp red wine vinegar', '2 tablespoons olive oil', '1 tsp sugar', '1/2 tsp black pepper', '1 pouch seven whole-grains mix', '2 cups rotisserie chicken', '1 cup grape tomatoes', '1/4 cup red onion', '1/4 cup fresh parsley', '1/4 cup fresh mint', '1 cucumber', '2 oz feta cheese'],
        'ingredients_subset': [],
        'directions': ['Prep: halve tomatoes, chop red onion, parsley, mint, and cucumber, and shred rotisserie chicken.', 'Whisk first 4 ingreients in large bowl. Add grains and toss. Add chicken and remaining ingredients.'],
        'photo': '/static/images/greek-chicken-tabbouleh-salad.jpg',
        'tags': ['Heather', 'Salad', 'Easy'],
        'formatted_tags': '',
        'source_name':'Weight Watchers',
        'source': '/static/sources/greek-chicken-tabbouleh-salad.jpg'
    },
    {
        'name': 'Chicken Salad',
        'ingredients': ['1 lb chicken breast', '1 1/4 cup chopped golden delicious, gala, or fuji apples', '1/3 cup chopped pecans', '1/3 cup dried cranberries', 'whole grain bread or lettuce wraps'],
        'ingredients_subset': ['5.3 oz fat-free plain greek yogurt', '2 tbsp mayo', '1 tbsp red wine vinegar', '2 1/2 tsp rosemary', '1 tsp dijon mustard', '1/2 tsp honey', '1/2 tsp onion powder', 'salt', 'pepper'],
        'directions': ['Preheat oven to 425 degrees F. Brush chicken with olive oil, salt, pepper, and bake for 16-23 min.', 'Dice chicken, chop pecans and apples.','Add chicken, apples, pecans, and cranberries to a large bowl. Mix dressing, add and toss.'],
        'photo': '/static/images/chicken-salad.jpg',
        'tags': ['Heather', 'Entree', 'Easy'],
        'formatted_tags': '',
        'source_name':'Cooking classy',
        'source': 'https://www.cookingclassy.com/apple-pecan-rosemary-greek-yogurt-chicken-salad/'
    },
    {
        'name': 'Greek Chicken Pasta Salad',
        'ingredients': ['2 chicken breasts', '8 oz shell pasta', '1 bell pepper', '4 oz grape tomatoes', '1/2 cucumber', 'fresh parsley', '2 oz feta'],
        'ingredients_subset': ['1 lemon', '1/4 cup olive oil', '3 cloves garlic', '1/2 tbsp oregano', 'salt', 'pepper'],
        'directions': ['Preheat oven to 425 degrees F. Brush chicken with olive oil, salt, pepper, and bake for 16-23 min.', 'Cook pasta, chop vegetables.', 'Add everything to a bowl and mix in dressing.'],
        'photo': '/static/images/greek-chicken-pasta-salad.jpg',
        'tags': ['Heather', 'Entree', 'Easy','Favorite'],
        'formatted_tags': '',
        'source_name':'Budget Bytes',
        'source': 'https://www.budgetbytes.com/greek-chicken-pasta-salad/'
    },
    {
        'name': 'Pork dumplings',
        'ingredients': ['100 wonton wrappers', '1 3/4 lbs ground pork', '1 tbsp fresh ginger', '4 cloves garlic', '2 tbsp green onion', '4 tbsp soy sauce', '3 tbsp sesame oil', '1 egg', '5 cups shredded Chinese cabbage'],
        'ingredients_subset': [],
        'directions': ['Mix filling in a large bowl.', 'Fold into wrappers.', 'Cook dumplings: heat oil over medium heat, add dumplings and cook until browned and crispy, 2-3 min. Flip and cook additional min. Add 1/3 cup water, reduce heat to medium, and cover. Steam 3-4 min.'],
        'photo': '/static/images/pork-dumplings.jpg',
        'tags': ['Heather', 'Entree', 'Asian'],
        'formatted_tags': '',
        'source_name':'All Recipes',
        'source': 'https://www.allrecipes.com/recipe/14759/pork-dumplings/'
    },
    {
	    'name': 'Harvest Skillet',
	    'ingredients': ['1 lb chicken breast', '4 thick-cut bacon', '3 cups Brussels sprouts', '1 sweet potato', '1 onion', '2 apples', '4 cloves garlic', '2 tsp fresh thyme', '1 tsp cinnamon', '1 cup chicken broth'],
	    'ingredients_subset': [],
	    'directions': ['Heat oil over medium high heat, add chicken, salt, and pepper. Cook ~5 min until lightly browned and cooked through, transfer to plate.', 'Reduce skillet to medium low, add bacon and cook ~8 min until done, transfer to plate. Discard all but 1 1/2 tbsp bacon fat from pan.','Increase skillet heat to medium high, add Brussels sprouts, sweet potato, onion, and salt. Cook ~10 min.', 'Stir in apples, garlic, thyme, and cinnamon, and cook 30 sec. Pour in 1/2 cup chicken broth, bring to a boil, cook until evaporated ~2 min.','Add the chicken and 1/2 cup chicken broth, cook ~2 min.', 'Add bacon and serve.'],
	    'photo': '/static/images/harvest-skillet.jpg',
	    'tags': ['Heather', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'Well Plated',
	    'source': 'https://www.wellplated.com/chicken-apple-sweet-potato-and-brussels-sprouts-skillet/',
	 },
	 {
	    'name': 'Tunisian Chickpea Stew',
	    'ingredients': ['3 tbsp olive oil', '1 onion', '3 carrots', '6 cloves garlic', '1 tbsp fresh thyme, sage, or bay leaves', '1 tsp cumin', '1 tsp coriander', '1 tsp smoked paprika', '1 tsp tumeric', '1 tsp fennel seeds', '2 tbsp tomato paste', '2 tomatoes', '1 cup white wine', '4 cups chicken broth', '4 cups chickpeas', '1 bunch kale', 'plain greek yogurt', 'harissa paste'],
	    'ingredients_subset': [],
	    'directions': ['Prep: dice onion, garlic, and tomatoes. Cut kale into 1-2 inch ribbons. Peel and cut carrots into 1/2 inch thick half moons','Heat oil in large pot over medium high heat, add onion, carrot, garlic, salt, and pepper. Saute for 5 min, turn heat to medium.','Add cumin, coriander, smoked paprika,tumeric, fennel seeds, and tomato paste. Saute ~2 min until darkens.', 'Add tomatoes and wine, bring to a boil, scrape up brown bits, reduce by half ~5 min.', 'Add broth.', 'Add chickpeas, kale, and carrot tops (optional). Simmer on medium-low for 10-15 min.', 'Serve in bowls and top with yogurt and harissa.'],
	    'photo': '/static/images/tunisian-chickpea-stew.jpg',
	    'tags': ['Heather', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'Feasting at Home',
	    'source': 'https://www.feastingathome.com/tunisian-chickpea-stew/',
	 },
	 {
	    'name': 'Lemony Orzo Salad',
	    'ingredients': ['1 box orzo pasta', '1 can chickpeas', '1 cucumber', '1 red onion', 'baby spinach', 'arugula', 'fresh basil', 'fresh mint', '2 lemons', 'feta or goat cheese' ],
	    'ingredients_subset': [],
	    'directions': ['Cook pasta, drain and rinse with cold water.', 'Prep: chop all other ingredients.', 'Combine everything in a bowl, zesting and juicing both lemons and adding salt, pepper, and olive oil. '],
	    'photo': '/static/images/lemony-orzo-salad.jpg',
	    'tags': ['Heather', 'Salad', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.gimmesomeoven.com/herb-lovers-lemony-orzo-salad/',
	 },
	 {
	    'name': 'Lemony Lentil Soup',
	    'ingredients': ['1 onion', '2 carrots', '5 cloves garlic', '6 cups chicken stock', '1 1/2 cups red lentils', '2/3 cups whole-kernel corn', '2 tsps cumin', '1 tsp curry powder', 'cayenne pepper', '1 lemon'],
	    'ingredients_subset': [],
	    'directions': ['Heat oil in a large pot over medium-high heat. Add onion and carrots, saute for 5 min. Add garlic and saute for 1 more min.','Stir in chicken stock, lentils, corn, cumin, curry powder, and cayenne. Cook until simmers, then for 15 min until lentils are completely tender.', 'Using a blender, puree the soup until it reaches desired consistency.','Return pureed soup to pot, stir in lemon zest and juice, add salt and pepper.'],
	    'photo': '/static/images/lemony-lentil-soup.jpg',
	    'tags': ['Heather', 'Salad', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.gimmesomeoven.com/lemony-lentil-soup/',
	 },
	 {
	    'name': 'Breakfast casserole',
	    'ingredients': ['12 eggs', '1 package shredded mozzerella cheese', '1/4 cup shredded parm', '1 can rotel diced tomatoes and green chilis', '1 lb sausage', '1 bunch kale (~8 oz)', 'garlic powder','Italian seasoning', 'Red pepper flakes'],
	    'ingredients_subset': [],
	    'directions': ['Preheat oven to 350 degrees F. Spray 13x9 pan with olive oil.', 'Cook sausage over medium heat in skillet until brown. Add red pepper and rotel, simmer ~5 min.', 'Remove sausage with slotted spoon and spread evenly over baking pan. Add kale to skillet with sausage grease/rotel juice and sprinkle with garlic powder, salt, and pepper. Stir 2-3 min until wilted, transfer to pan, let cool.', 'Beat 12 eggs in mixing bowl, add salt, pepper, and Italian seasoning.', 'Add layer of 1/2 package of mozzarella to the pan, add egg mixture to the pan, add rest of mozzarella and parm to the top. Sprinkle with Itallian seasoning.','Bake uncovered ~35-45 min. Can refrigerate overnight before baking, serves 8-10.'],
	    'photo': '/static/images/breakfast-casserole.jpg',
	    'tags': ['Heather'],
	    'formatted_tags': '',
	    'source_name':'Katherine Lalla',
	    'source': '/static/sources/breakfast-casserole.png',
	 },
	 {
	    'name': 'Pasta with Pears & Gorgonzola',
	    'ingredients': ['12 oz rigatoni', '1/3 cup walnut pieces', '4 tbsp unsalted butter', '4 Bosc pears', '1/2 cup vegetable broth', '4 oz crumbed gorgonzola or goat cheese', '1/4 cup dried cranberries'],
	    'ingredients_subset': [],
	    'directions': ['Prep: boil water for pasta. Peal and core pears, cut lengthwise into 8 wedges.', 'Cook pasta, reserving 1/2 cup pasta water.', 'Heat oil in large skillet over medium heat, add walnuts and cook ~5 min then transfert to plate.', 'Add butter to skillet, once melted add pears. Cook until pears lightly brown, ~5 min. Transfer to a plate, leaving liquid in skillet.', 'Add broth to skillet, deglaze bottom of pan, add cheese and bring to a simmer. Whisk until cheese melts and sauce reduces slightly, ~5 min.', 'Add the pasta and 1/4 cup reserved pasta water to skillet, reduce heat to low and toss. Add remaining pasta water 1 tbsp at a time as needed, texture should be creamy and fluid.', 'Plate add top with pears, walnuts, and cranberries. Season with salt and pepper, can add more cheese to top.'],
	    'photo': '/static/images/pasta-pear-gorgonzola.png',
	    'tags': ['Heather', 'Entree', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Kate Leland',
	    'source': '/static/sources/pasta-pear-gorgonzola.jpg',
	 },
	 {
	    'name': 'Tacos',
	    'ingredients': ['1 lb ground beef', 'tomatoes', 'onions', 'lettuce', 'taco seasoning', 'soft taco shells', 'sour cream', 'shredded cheese', 'hot sauce'],
	    'ingredients_subset': [],
	    'directions': ['Cook beef with seasoning and hot sauce.', 'Assemble tacos and serve.'],
	    'photo': '/static/images/tacos.jpg',
	    'tags': ['Heather', 'Entree', 'Easy', 'Favorite'],
	    'formatted_tags': '',
	    'source_name':'Kevin <3',
	    'source': '',
	 },
	 {
	    'name': 'Vegetarian Chili',
	    'ingredients': ['1 onion', '1 red bell pepper', '1 green bell pepper', '2 carrots', '3 cloves garlic', '1 jalapeño', '1 tbsp tomato paste', '1 15.5 oz can pinto beans', '1 can black beans', '1 can kidney beans', '1 28 oz can tomatoes', '3 cups vegetable broth', '2 tbsp chili powder', '1 tbsp cumin', '2 tsp oregano', 'shredded cheddar cheese', 'sour cream', 'cilantro'],
	    'ingredients_subset': [],
	    'directions': ['Prep: Chop the onion, peppers, carrots, and jalapeño. Mince the garlic. Drain and rinse the beans.', 'In large pot, heat olive oil over medium high heat and add onion, bell peppers, and carrots. Saute ~5 min then add garlic and jalapeño, cook 1 min.', 'Stir in tomoato paste. Stir in tomatoes, beans, broth, spices, salt, and pepper.', 'Bring to a boil then reduce heat and simmer for 30 min.', 'Serve and top with cheese, sour cream, and cilantro.'],
	    'photo': '/static/images/vegetarian-chili.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Delish',
	    'source': 'https://www.delish.com/cooking/recipe-ideas/recipes/a58719/easy-vegetarian-chili-recipe/',
	 },
	 {
	    'name': 'Cheese boregs',
	    'ingredients': ['8 oz Muenster or Monterey Jack cheese', '15 oz ricotta cheese', '4 oz feta cheese', '1 egg', '1 pkg Fillo dough', '1/2 stick unsalted butter', 'parsley'],
	    'ingredients_subset': [],
	    'directions': ['Defrost the Fillo dough. Preheat oven to 350 degrees F.','Mix the cheese, egg, and parsley in a big bowl.', 'Unfold the Fillo dough and cut in half. Use one sheet for each boreg: fold in half lengthwise, brush surface with melted butter, place a spoonful of filling at the end of the folded dough, fold as though you were folding a flag - on the diagonal from corner to corner, creating a triangular shape. Brush top with butter and place on baking sheet.', 'Bake for 15-20 min.'],
	    'photo': '/static/images/cheese-boregs.jpg',
	    'tags': ['Heather', 'Vegetarian', 'Small Plate', 'Armenian'],
	    'formatted_tags': '',
	    'source_name':'The Armenian Kitchen',
	    'source': 'https://www.thearmeniankitchen.com/2009/04/borag-bereg-boregthey-all-spell.html',
	 },
	 {
	    'name': 'Teriyaki Chicken Wings',
	    'ingredients': ['1-2 pkg chicken wings', '1 bottle LeeKum Kee chicken marinade', 'garlic powder', 'onion powder'],
	    'ingredients_subset': [],
	    'directions': ['Preheat oven to 350 degrees F.', 'Add wings, 1/2 - 2/3 bottle of marinade, onion powder, and garlic powder to a zip lock bag to mix.', 'Marinate 18-24 hours, shaking/mixing every 4-6 hours.','Bake 45-50 min.'],
	    'photo': '/static/images/teriyaki-chicken-wings.jpg',
	    'tags': ['Heather', 'Small Plate'],
	    'formatted_tags': '',
	    'source_name':'Aunt Ginny',
	    'source': '/static/sources/teriyaki-chicken-wings.pdf',
	 },
	 {
	    'name': 'Pasta Salad',
	    'ingredients': ['1 box rotini', '1 cucumber', 'grape tomatoes', '1/3 block cheddar cheese', '1 ball mozzarella cheese', '1 green bell pepper', '1 red bell pepper'],
	    'ingredients_subset': ['1/2 cup olive oil' '1/4 cup red wine vinegar', '2 cloves garlic', '1 tsp dried basil', '1 tsp dried oregano', '1/2 tsp ground mustard seed', '1/4 tsp salt', '1/8 tsp black pepper'],
	    'directions': ['Chop vegetables','Cook, drain, and rinse pasta.', 'Mix together in big bowl and add dressing.'],
	    'photo': '/static/images/pasta-salad.jpg',
	    'tags': ['Heather', 'Entree', 'Vegetarian', 'Easy', 'Favorite'],
	    'formatted_tags': '',
	    'source_name':'All recipes',
	    'source': 'https://www.allrecipes.com/recipe/73963/pasta-salad-with-homemade-dressing/',
	 },
	 {
	    'name': 'Chai Butternut Squash Soup',
	    'ingredients': ['2 cups vegetable stock', '2 cloves garlic', '1 carrot', '1 apple', '1 medium butternut squash', '1 small white onion', '1/8 tsp cayenne', '1-2 chai tea bags', '1/2 cup coconut milk', 'cinnamon'],
	    'ingredients_subset': [],
	    'directions': ['Prep: mince garlic, dice carrot, apple, squash, and onion.','Add vegetable stock, garlic, carrot, apple, squash, onion, cayenne, and chai tea bags to large pot. Cook 3-4 hours on high.', 'Remove tea bags, puree the soup until smooth, stir in coconut milk, add salt and pepper.','Serve and top with cinnamon and optional swirl of coconut milk.'],
	    'photo': '/static/images/chai-butternut-squash-soup.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.gimmesomeoven.com/chai-butternut-squash-soup/',
	 },
	 {
	    'name': 'Cajun Corn Chowder',
	    'ingredients': ['1 medium white onion', '1 green bell pepper', '2 ribs celery', '4 cloves garlic', '6 cups vegetable stock', '1 1/2 lbs Yukon potatoes', '14 oz corn', '1 cup red lentils *', '1 tsp dried thyme', '14 oz coconut milk', 'optional toppings: green onions, bacon, oyster crackers'],
	    'ingredients_subset': ['paprika', 'salt', 'garlic powder', 'ground black pepper', 'onion powder', 'dried oregano', 'cayenne', 'thyme'],
	    'directions': ['Prep: dice onion, bell pepper, and celery. Mince garlic. Dice potatoes into 1/2 inch cubes.','Heat oil in large pot over medium-high heat.', 'Add onion and saute for 3 min. Add bell pepper, celery and garlic, and saute for 5 more min.', 'Stir in vegetable stock, potatoes, corn, lentils, cajun seasoning, thyme, and salt.','When simmers, reduce heat to medium-low and cook for 10-15 min, stirring occassionally, until potatoes and lentils tender. Stir in coconut milk.', 'Serve with toppings.', '* Whole red lentils take about 15 minutes to cook.  Split red lentils only take ~7-8 min, so if using those then add them halfway through the potatoes’ cooking time.'],
	    'photo': '/static/images/cajun-corn-chowder.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.gimmesomeoven.com/cajun-corn-chowder/',
	 },
	 {
	    'name': 'Thai Yam Soup',
	    'ingredients': ['2 large shallots or 1 white onion', '2 tbsp coconut oil', '6 cloves garlic', '1/2 cup lemongrass', '1/4 cup ginger', '1 small spicy chili', '1 tsp yellow curry powder', '1/2 tsp tumeric', '4 cups vegetable or chick stock', '2 cups water', '2 lbs yams or sweet potatoes', '1 carrot', '1/2 cup coconut milk', '2 tsp brown sugar', '3 tsp soy or fish sauce', '2 tbsp lime juice','optional garnishs: cilantro, coconut milk, scallions, Sriracha, lime'],
	    'ingredients_subset': [],
	    'directions': ['Prep: dice shallot or onion, chili, and carrot; finely chop garlic, lemongrass, and ginger; peel and cube yams.','Heat coconut oil in large pot over medium heat. Add shallot or onion and stir 2 min. Add ginger, garlic, lemongrass, and chili and cook 3-5 min. Add spices, cook 1-2 min. Add stock, scrape bottom of pot.', 'Bring to a boil, add yam and carrot. Simmer covered until yams are tender, ~15-20 min.', 'Puree soup, return to stove on medium low, stir in 1/2 cup coconut milk. Add brown sugar, soy/fish sauce, lime juice, and Sriracha.', 'Serve and garnish with cilantro, scallions, coconut milk, lime wedges.'],
	    'photo': '/static/images/thai-yam-soup.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.feastingathome.com/thai-yam-soup-w-lemongrass-ginger-and-sorghum-flowers/',
	 },
	 {
	    'name': 'Steaks',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/steak.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Chicken Parm',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/chicken-parm.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Teriyaki Chicken Bowl',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/teriyaki-chicken-bowl.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Roasted Chicken',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/roasted-chicken.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Irish Soda Bread',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/irish-soda-bread.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Mushroom Risotto',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/mushroom-risotto.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'All Recipes',
	    'source': 'https://www.allrecipes.com/recipe/85389/gourmet-mushroom-risotto/',
	 },
	 {
	    'name': 'Cola Chicken Wings',
	    'ingredients': [],
	    'ingredients_subset': [],
	    'directions': [''],
	    'photo': '/static/images/cola-chicken-wings.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'',
	    'source': '',
	 },
	 {
	    'name': 'Pasta',
	    'ingredients': ['flour', '2-4 eggs', 'olive oil', 'salt'],
	    'ingredients_subset': [],
	    'directions': ['Make a crater in the center of a mound of flour.','In the center, add eggs, oil, and salt.','Using a fork, slowly work the wet ingredients into the flour from the inside-out.','Once doughy, knead with hands.','Roll out dough, run through pasta maker to thin and cut, cook for ~5 min.'],
	    'photo': '/static/images/pasta.jpg',
	    'tags': ['Kevin', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'Gimme Some Oven',
	    'source': 'https://www.gimmesomeoven.com/homemade-pasta/',
	 },
	 {
	    'name': 'Allepo Dill Pickles',
	    'ingredients': ['8 persian cucumbers', '1/4 cup dill', '2 1/2 cups distilled whtie vinegar', '1/3 cup sugar', '1 garlic clove', '1 tbsp Aleppo red pepper', '1 tbsp lemon juice', '1 tbsp salt', '1 tsp crushed red pepper flakes', '1 tsp black pepper', 'za\'atar'],
	    'ingredients_subset': [],
	    'directions': ['Pack cucumber and dill into large heatproof jar.', 'Bring vinegar, sugar, garlic, Aleppo pepper, lemon juice, salt, red pepper flakes, and black pepper to a boil in medium saucepan, stirring to dissolve sugar.', 'Let cool slightly, pour brine over cucumbers to submerge. Seal jar and chill at least 30 min.', 'Remove cucumbers from brine, lightly shake off extra liquid, sprinkle with za\'atar and salt. Serve.'],
	    'photo': '/static/images/pickles.jpg',
	    'tags': ['Heather', 'Small Plate', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Bon Appetit',
	    'source': 'https://www.bonappetit.com/recipe/quick-aleppo-dill-pickles',
	 },
	 {
	    'name': 'Butternut Squash and Apple Soup',
	    'ingredients': ['1 medium butternut squash', '1/4 lb unsalted butter', '1/4 tsp cinnamon', '1/4 tsp nutmeg', '1 medium yellow onion', '1 apple, preferably Mac, Granny Smith, or Gala', '1 1/2 cups chicken broth or stock', '2 cups water', '1 1/2 cups apple cider'],
	    'ingredients_subset': [],
	    'directions': ['Preheat oven to 425 degrees F.', 'Prep: dice onion and apple. Split squash in half lengthwise and scoop out seeds.', 'Bake squash: melt 1/2 butter, rub on squash, season with salt, pepper, cinnamon, and nutmeg. Place squash skin side up on baking sheet and roast for 45 min. When finished, cool and then scoop out meat and discard skin.', 'Cook: melt remaining butter in large pot, add onion and apple. Season with salt and pepper, cook over medium until soft, add squash.', 'Add stock, water, and cider. Bring to a boil, reduce to low and simmer ~20 min.', 'Puree and serve.'],
	    'photo': '/static/images/squash-apple-soup.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Boston Chefs',
	    'source': 'https://www.bostonchefs.com/recipe/brian-dandro-butternut-squash-and-apple-soup/',
	 },
	 {
	    'name': 'Stovetop Mac & Cheese',
	    'ingredients': ['1 1b elbow macaroni', '12 oz evaporated milk', '2 eggs', '1 tsp hot sauce', '1 tsp ground mustard', '1 lb shredded cheddar cheese', '8 oz cubed American cheese', '1 tbsp cornstarch', '1 stick unsaltd butter'],
	    'ingredients_subset': [],
	    'directions': ['Boil water for pasta.','Whisk together evaporated milk, eggs, hot sauce, and mustard in a bowl.', 'In another bowl, toss cheeses with cornstarch.', 'Cook and drain pasta, return to pot on low heat, add butter and stir until melted. Add milk and cheese mixtures, stir until melted.', 'Season with more salt and hot sauce as needed and serve.'],
	    'photo': '/static/images/stovetop-mac-and-cheese.jpg',
	    'tags': ['Heather', 'Entree', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Andrew Baber, via Serious Eats',
	    'source': 'https://www.seriouseats.com/recipes/2015/10/the-food-labs-ultra-gooey-stovetop-mac-cheese.html',
	 },
	 {
	    'name': 'Sarawak Laksa',
	    'ingredients': ['8 oz rice vermicelli', '16-20 jumbo shrimps', '2 quarts chicken stock', '3/4 cup Sarawak Laksa paste', '2 eggs', '1 tbsp soy sauce', '3/4+ cups coconut milk', '2 cups bean sprouts', '1 large bone-in chicken breast', 'cilantro', 'lime', 'chili peppers', 'optional: sambal belacan'],
	    'ingredients_subset': [],
	    'directions': ['Make shrimp stock: cover shrimp shells in water, bring to a boil, simmer 20 min.', 'Cook chicken: boil chicken stock, add chicken, reduce to a simmer and cook 12 min. Turn off heat, cover pot, set aside 12-15 min. When cool enough, shred and set aside chicken meat, discarding bones.', 'Enhance stock: stir laksa paste into stock. Using strainer to hold back shells, add shrimp stock to chicken stock/laksa paste mixture. Cover and simmer on low for 30 min.', 'Make eggs: whisk 2 eggs and soy sauce in a bowl. Heat oil in a pan over medium heat, pour egg mixture in, cook 2 min, flip over and turn off heat. Once cooked, let cool, cut into strips and set aside.', 'Make noodles: place rice vermicelli in a bowl, pour in hot water and let sit for 5 min. Agitate slightly to keep from sticking, drain, toss in small amount of oil and set aside.', 'Finish stock: strain stock though a seive, return to high, add shrimp. After 30 sec, remove shrimp and set aside. Add coconut milk, bring to a boil, remove from heat.','Serve: divide bean sprouts, chicken, shrimp, egg, and vermicelli between 4 bowls. Pour in broth and top with cilantro, lime, chili peppers, and sambal belacan.'],
	    'photo': '/static/images/sarawak-laksa.jpg',
	    'tags': ['Heather', 'Entree', 'Asian'],
	    'formatted_tags': '',
	    'source_name':'Anthony Bourdain',
	    'source': 'http://www.passmethedimsum.com/2017/01/15/laksa-recipe-anthony-bourdain/',
	 },
	 {
	    'name': 'Baked Mac and Cheese',
	    'ingredients': ['1 box elbows', '2 lbs sharp chedder cheese', '2 eggs', '1 cup whole milk', 'butter'],
	    'ingredients_subset': [],
	    'directions': ['Preheat oven 350 degrees F. Grease 9x13 pan. Cook noodles. Grate cheese.', 'Mix eggs and milk. Add noodles and 1 1/2 lbs cheese. Add a few butter slices on top.','Bake covered for 40 min.', 'Add remaining cheese and bake 20 more min.'],
	    'photo': '/static/images/baked-mac-and-cheese.jpg',
	    'tags': ['Heather', 'Entree', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Katherine Lalla',
	    'source': '/static/sources/baked-mac-and-cheese.jpg',
	 },
	 {
	    'name': 'Gumbo',
	    'ingredients': ['1 cup vegetable oil', '1 cup flour', '1 lb andouille sausage', '1 bag frozen diced okra', '1 large onion', '1 large green bell pepper', '2 tbsp garlic', '1 large rotisserie chicken', '1 can rotel diced tomatoes with green chilies', '6 cups chicken broth', '8 oz clam juice', '3 dried bay leaves', 'Tabasco', 'Worcestershire', '1 lb shrimp', '1 pint shucked oysters', 'green onions', 'parsley'],
	    'ingredients_subset': ['white rice', 'warm bread', 'seasonal salad'],
	    'directions': ['Begin preparations at least 1 day prior to serving.', 'Prep: slice susage into 1/2 circles. Chop onion, pepper. Mince garlic. Remove and shred meat from chicken.', 'Start stock: in large stock pan, heat chicken broth, clam juice, and 2 dashes of Tabasco over low heat on back burner. Should warm but not boil.', 'Cook sausage and okra: cook sausage in a cast iron skillet, remove and set aside. Add frozen okra, cook in sausage juices until browned, set aside.','Make roux: microwave oil for 20-30 sec to start warming. Add to dutch oven over low-medium (2-3) heat. Whisk in flour, constantly stirring and scraping the bottom with the flat edge of a wooden spatula for 45 min. If you start to get brown bits, it\'s burning - start over.','Roux should have turned from light and cloudy to copper, increase heat slightly (3-4) and stir 30 more min until caramel color and totally smooth.','Remove roux from heat and stir 10 more min. Slowly ladle in broth, still stirring constantly, for 30 min. Return pot to burner over low-medium heat (3-4) and keep stirring.', 'Saute veggies: add onions, bell pepper, and garlic to warm broth pan and saute ~10-15 min, while still stirring roux.', 'Add everything to roux: slowly add sauted veggies to roux over the course of 10-15 min, still stirring constantly. Add rotel, bay leaves, 2 large dashes Worcestershire sauce, still stirring. Slowly add cooked sausage, chicken, and okra and stir for 30 more min.', 'Wrap up day 1: stir for an additional 15 min over heat if needed. Remove from heat and stir 10-15 min to start to cool off, then let rest for 30-45 min and refrigerate overnight, ideally for 24 hours.','Start cooking rice. Remove gumbo from fridge and place on low-medium heat (3-4) and stir every 3-5 min. Once it\'s hot (might take 30-45 min), add shrimp and stir until pink, ~5-10 min.','Cook oysters: heat oil over high heat in cast iron skillet and add oysters 3-5 at a time for 20-30 seconds to heat and slightly brown.', 'Serve with 1/4 - 1/2 cup rice per bowl, top generously with gumbo and 2-3 oysters, garnish with scallions and parsley. Serve with seasonal salad and warm bread.' ],
	    'photo': '/static/images/gumbo.jpg',
	    'tags': ['Heather', 'Entree'],
	    'formatted_tags': '',
	    'source_name':'Katherine Lalla',
	    'source': '/static/sources/gumbo.pdf',
	 },
	 {
	    'name': 'Moroccan Lentil & Vegetable Soup',
	    'ingredients': ['1 tbsp olive oil', '1 cup onion', '4 cloves garlic', '1/2 cup dried lentils', '1 1/2 tsp corriander', '1 1/2 tsp cumin', '1/2 tsp cinnamon', '1/2 tsp black pepper', '32 oz vegetable broth', '1/2 cup celery', '1/2 cup sun-dried tomatoes (not in oil)', '1 yellow squash', '1/2 cup green bell pepper', '1 cup plum tomatoes', '1/2 cup fresh Italian parsley', '1/4 cup fresh cilantro or basil'],
	    'ingredients_subset': [],
	    'directions': ['Prep: chop onion, celery, sun-dried, tomatoes, squash, green bell pepper, plum tomatoes, parsley and cilatnro/basil. Mince garlic. Rinse and sort lentils.', 'Heat oil in medium sauce panover medium-high heat. Add onion and garlic, cook ~4 min. Stir in coriander, cumin, cinnamon, and black pepper, cook 2 min. Add broth, celery, and sun-dried tomatoes. Bring to a boil, reduce heat to medium-low, cover and simmer 25 min.', 'Stir in squah and bell pepper, cover and cook until lentils tender, ~10 min.', 'Serve and top with tomatoes, parsley, and cilantro/basil.'],
	    'photo': '/static/images/moroccan-lentil-soup.jpg',
	    'tags': ['Heather', 'Soup', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Diabetes Self Management Magazine',
	    'source': '/static/sources/mediterranean.jpg',
	 },
	 {
	    'name': 'Hummus',
	    'ingredients': ['15 oz chickpeas', '2 tbsp tahini', '2 tbsp lemon juice', '1 clove garlic', '3/4 tsp salt'],
	    'ingredients_subset': [],
	    'directions': ['Prep: rinse and drain chickpeas, mince garlic.', 'Combine chickpeas, tahini, lemon juice, garlic, and salt in food processor or blender, process until smooth.', 'Mix in olive oil and serve.'],
	    'photo': '/static/images/hummus.jpg',
	    'tags': ['Heather', 'Small Plate', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Diabetes Self Management Magazine',
	    'source': '/static/sources/mediterranean.jpg',
	 },
	 {
	    'name': 'Greek Side Salad',
	    'ingredients': ['1 can cannellini beans', '1 pkg grape tomatoes', '1 cucumber', '2 tbsp red onion', '1 bell pepper', '1 pkg crumbled feta'],
	    'ingredients_subset': ['olive oil', 'balsamic vinegar', 'salt', 'pepper'],
	    'directions': ['Prep: halve tomatoes; chop cucumber, green pepper, and onion; drain and rinse beans.','Mix salad ingredients together, add dressing, serve.'],
	    'photo': '/static/images/greek-side-salad.jpg',
	    'tags': ['Heather', 'Small Plate', 'Salad', 'Vegetarian'],
	    'formatted_tags': '',
	    'source_name':'Diabetes Self Management Magazine',
	    'source': '/static/sources/mediterranean.jpg',
	 },
	{
        'name': 'Brie bites',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/brie-bites.jpg',
        'tags': ['Heather', 'Small Plate', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Delish',
        'source': 'https://www.delish.com/cooking/recipe-ideas/recipes/a56610/cranberry-brie-bites-recipe/',
     },
     {
        'name': 'Bacon and Beef Stew',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/bacon-and-beef-stew.jpg',
        'tags': ['Kevin', 'Bon Appetit', 'Soup', 'Entree'],
        'formatted_tags': '',
        'source_name':'Bon Appetit',
        'source': 'https://www.bonappetit.com/recipe/beef-and-bacon-stew',
     },
     {
        'name': 'Matzo Ball Soup',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/matzo-ball-soup.jpg',
        'tags': ['Kevin', 'Soup'],
        'formatted_tags': '',
        'source_name':'',
        'source': '',
     },
     {
        'name': 'Halifax Donair',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/donair.jpg',
        'tags': ['Kevin', 'Entree'],
        'formatted_tags': '',
        'source_name':'Matty Matheson',
        'source': 'https://www.youtube.com/watch?v=LXXUqe9JiY8&list=PLxg70CyF67NjdKXOy0THz8u5ivGSKYK3-&index=5&t=0s',
     },
     {
        'name': 'Shrimp Stir Fry',
        'ingredients': ['1 lb shrimp', '1 red bell pepper', '3/4 cup chicken broth', '1 tsp flour', '2 cups broccoli florets', '1 cup sugar snap peas', 'green onion', 'sesame seeds', 'rice'],
        'ingredients_subset': ['1/4 cup soy sauce', '3 cloves garlic', '3 tbsp brown sugar', '1 tsp sesame oil'],
        'directions': ['Make the rice.', 'Prep: mince garlic, slice pepper, peel shrimp.', 'Make sauce: whisk together soy sauce, garlic, brown sugar, and sesame oil.', 'In wok heat oil over medium-high heat and add the shrimp, pepper, and sauce. Cook until shrimp is pink (2-3 min).', 'Whisk chicken broth and cornstarch together, add to wok.', 'Add broccoli and snap peas to wok. Stir and cook 3-5 min, until broccoli tender and sauce thickens.', 'Top with green onions and sesame seeds, serve.'],
        'photo': '/static/images/shrimp-stir-fry.jpg',
        'tags': ['Heather', 'Entree', 'Asian'],
        'formatted_tags': '',
        'source_name':'The Recipe Critic',
        'source': 'https://therecipecritic.com/garlic-shrimp-stir-fry/',
     },
     {
        'name': 'Chicken Marsala',
        'ingredients': ['4 chicken breasts', '4 oz proscuitto', '8 oz crimini or procini mushrooms', '1/2 cup sweet Marsala wine', '1/2 cup chicken stock', '2 tbsp butter', '1/4 cup parsley'],
        'ingredients_subset': [],
        'directions': ['Mix together flour, salt, and pepper in a bowl.', 'Heat oil in large skillet over medium-high heat. Coat chicken breasts in seasoned flour and add to skillet, frying for 5 min on each side. Remove when done.', 'Lower the heat to medium, add proscuitto and saute 1 min. Add mushrooms and saute 5 min, season with salt and pepper.', 'Pour in the Marsala and boil down for a few seconds, then add chicken stock and simmer for 1 min.', 'Add butter, add chicken back in, simmer 1 min.', 'Top with parsley and serve.'],
        'photo': '/static/images/chicken-marsala.jpg',
        'tags': ['Heather', 'Entree'],
        'formatted_tags': '',
        'source_name':'Food Network',
        'source': 'https://www.foodnetwork.com/recipes/tyler-florence/chicken-marsala-recipe-1951778',
     },
     {
        'name': 'Lemon Chicken',
        'ingredients': ['4 chicken breasts', '1/3 cup flour', '4 tbsp butter', '1/4 cup chicken broth', '4 lemons', 'parsley', 'asparagus or green beens', '2 cloves garlic'],
        'ingredients_subset': [],
        'directions': ['Cook green beans or asparagus with olive oil and garlic.', 'Cut chicken breasts in half and flatten to 1/4 inch thickness. Season with salt and pepper, lightly dredge in flour.', 'Melt 1 tbsp butter with 1 tbsp olive oil in large skillet over medium-high heat. Cook half the chicken until golden brown, ~2-3 min on each side. Transfer chicken to platter and cook the other 1/2 of the chicken in another tbsp of butter and olive oil.', 'Add broth and 1/4 cup lemon juice to skillet, cook 1-2 min until sauce thickens and add 8 lemon slices.', 'Remove skillet from heat, add parsley and 2 tbsp of butter. Stir until melted, pour sauce over chicken, and serve.'],
        'photo': '/static/images/lemon-chicken.jpg',
        'tags': ['Heather', 'Entree'],
        'formatted_tags': '',
        'source_name':'My Recipes.com',
        'source': 'https://www.myrecipes.com/recipe/lemon-chicken',
     },
     {
        'name': 'Leek, Potato, & Cheddar Soup',
        'ingredients': ['3 leeks', '3 Yukon Gold potatoes', '4 cups chicken broth', '2 cups whole milk', 'pinch of ground nutmeg', '1/2 cup sharp cheddar cheese'],
        'ingredients_subset': ['onion', 'celery', 'bacon', 'green onions'],
        'directions': ['Prep: peel and dice potatoes. Slice leeks, keep white and light green parts only.', 'Heat oil in large saucepan over meium-high heat. Add leeks, salt, and pepper and cook ~5 min. Add potatoes and broth and bring to a boil.', 'Reduce heat to medium-low and simmer until potatoes soften, ~8-10 min. Add milk and nutmeg, stir and cook ~3 min.', 'Remove 2 cups of soup and puree in blender until smooth. Return puree to saucepan, add cheese and stir in until melts. Serve.'],
        'photo': '/static/images/leek-potato-cheddar-soup.jpg',
        'tags': ['Heather', 'Soup'],
        'formatted_tags': '',
        'source_name':'Clean Eating Magazine',
        'source': 'https://www.foodnetwork.com/recipes/tyler-florence/chicken-marsala-recipe-1951778',
     },
     {
        'name': 'Taco Dip',
        'ingredients': ['8 oz cream cheese', '1 can chile, beans, or cooked beef', 'shredded cheddar', 'lettuce', 'tomatoes', 'chips'],
        'ingredients_subset': [],
        'directions': ['Prep: shred lettuce and dice tomatoes', 'Microwave cream cheese, chile/beans/beef, and cheddar until cheese melts. Top with lettuce and tomatoes.'],
        'photo': '/static/images/taco-dip.jpg',
        'tags': ['Heather', 'Small Plate', 'Mexican'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/taco-dip.jpg',
     },
     {
        'name': 'Tortellini Soup',
        'ingredients': ['8 cups chicken broth', 'zucchini', '1 pkg chicken proscuitto tortellini', 'parsley', 'basil', 'thyme'],
        'ingredients_subset': [],
        'directions': ['In large pot, heat broth, zucchini, salt, and pepper over medium-high heat until boiling.', 'Add tortellini and cook 5 min.', 'Remove from heat, add herbs, and serve.'],
        'photo': '/static/images/tortellini-soup.jpg',
        'tags': ['Heather','Soup'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/tortellini-soup.jpg',
     },
     {
        'name': 'Kufte Yakhenie',
        'ingredients': ['1 lb ground lamb', '1/3 cup onion', '1 tsp Cayenne pepper', '1/2 tsp paprika', '2 1/3 cup bulghour (fine)', '1/2 stick butter'],
        'ingredients_subset': ['2 quarts chicken broth', '2 tbsp dried mint', '1 quart madzoon (plain yogurt)', '1 egg'],
        'directions': ['Make kuftes: finely chop onion. Mix meat, onion, salt, cayenne pepper, paprika, and 2 tbsp cold water for 1 min. Add bulghour slowly, kneading and adding water occassionally (up to 1 cup) for 15 min.', 'Form kuftes into balls, stuff each with dab of butter and some black pepper.', 'Boil 2 quarts chicken broth, add kuftes (broth should cover them), bring to boil and simmer 5 min.', 'Mix madzoon and egg together in a saucepan. Gradually add 1/3 kufte broth to madzoon mixture, stirring constantly. Mix thoroughly and pour back into the pot.', 'Mix in mint and serve.'],
        'photo': '/static/images/kufte-yakhenie.jpg',
        'tags': ['Heather', 'Soup', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/kufte-yakhenie.jpg',
     },
     {
        'name': 'Three-Bean Salad',
        'ingredients': ['16 oz red kidney beans', '16 oz green beans', '16 oz wax beans', '16 oz white beans', '1 onion', '1/2 green bell pepper', '1/2 cup celery', '4 oz pimentos'],
        'ingredients_subset': ['1/2 cup sugar', '1/2 cup vinegar', '1/2 cup olive oil', '1/2 tsp salt', '1/2 tsp Worcestershire', '1/2 tsp black pepper'],
        'directions': ['Prep: drain and rinse beans and pimentos, thinly slice onion, green pepper, and celery.', 'Make dressing: in small bowl, beat together until blended and sugar dissolved.', 'In large bowl, toss everything together and chill several hours. Drain excess dressing before serving.'],
        'photo': '/static/images/three-bean-salad.jpg',
        'tags': ['Heather', 'Small Plate', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/three-bean-salad.jpg',
     },
     {
        'name': 'Mom\s Mac and Cheese with Ham',
        'ingredients': ['2 tbsp butter', '1/4 cup flour', '1/2 tsp ground mustard seed', '1/4 tsp pepper', '1 tsp salt', '2 1/2 cups milk', '2 cups grated cheddar cheese', '8 oz macaroni', '1/4 cup bread crumbs', 'cubed ham'],
        'ingredients_subset': [],
        'directions': ['Prreheat oven to 375 degrees F. Dice ham, cook and drain macaroni.', 'In saucepan, melt butter over low heat. Stir in flour, salt, mustard, and pepper until smooth. Stirring constantly, cook over medium heat ~10 min or until thickened. Remove from heat, stir in 1 1/2 cup cheese until melted.', 'Grease 2-quart casserole dish and pour in cooked macaroni. Pour cheese mix and ham over macaroni, mix will. Sprinkle bread crumbs over top and bake for 25 min.'],
        'photo': '/static/images/mac-and cheese-ham.jpg',
        'tags': ['Heather','Entree', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/mac-and cheese-ham.jpg',
     },
     {
        'name': 'Stir Fry',
        'ingredients': ['1/2 cup chicken stock', '1/2 cup tamari', '1 inch ginger', '1 lemon', '1 cup orange marmalade', '3 tbsp canola oil', '2 lbs chicken', '1 red bell pepper', '1 cup peas', '1 cup shredded carrots', '4 cups cooked rice'],
        'ingredients_subset': ['beef', 'broccoli', 'peppers', 'water chestnuts', 'pineapple'],
        'directions': ['Prep: peel ginger, slice bell pepper, cut up chicken. Make the rice.', 'In medium saucepan over high heat combine stock, tamari, ginger, marmalade, and black pepper. Bring to a bubble, reduce heat to medium and reduce until thicked, ~20min. Remove from heat, stir in lemon juice, and reserve.', 'Heat oil in large skillet over medium-high heat. When hot, add meat and cook 7-8 min (5-6 for shrimp), transfer to plate and reserve.', 'Return skillet to heat and cook vegetables, 4-5 min. Add heat and sauce back in, toss and serve.'],
        'photo': '/static/images/stir-fry.jpg',
        'tags': ['Heather','Entree', 'Asian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/stir-fry.jpg',
     },
     {
        'name': 'Macaroni Salad',
        'ingredients': ['8 oz macaroni', '1 cup celery', '2 tbsp pimento', '2 tbsp green bell pepper'],
        'ingredients_subset': ['2/3 cup mayo', '2 tbsp cide vinegar', '1 tsp salt', '1/2 tsp celery seed', '1/8 tsp black pepper'],
        'directions': ['Prep: thiny slice celery, chop pimento and green pepper.', 'Cook, drain, and rinse macaroni with cold water.', 'Stir together mayo, vinegar, salt, celery seed, and black pepper.', 'Add macaroni, celery, pimento, and green pepper.', 'Toss, cover, chill, and serve.'],
        'photo': '/static/images/macaroni-salad.jpg',
        'tags': ['Heather','Small Plate','Vegetarian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/macaroni-salad.jpg',
     },
     {
        'name': 'Vegetarian Chili 2',
        'ingredients': ['40 oz kidney beans', '15 oz chickpeas or cannellini beans', '2 cloves garlic', '1 onion', '8 oz tomato sauce', '14 oz can whole peeled tomatoes', '1 tbsp thyme', '1 tsp cumin', '1/2 tsp basil', '3 tbsp chili powder'],
        'ingredients_subset': [],
        'directions': ['Prep: mince garlic, chop garlic, rince and drain beans.', 'In large pot, heat oil and saute garlic and onion. Add beans and remaining ingredients, bring to a boil and simmer 20 min.'],
        'photo': '/static/images/vegetarian-chili-2.jpg',
        'tags': ['Heather','Soup', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/vegetarian-chili.jpg',
     },
     {
        'name': 'Potato Salad',
        'ingredients': ['12 potatoes', '2 1/2 tbsp dijon mustard', '1/2 cup sweet pickle juice', '4 tbsp olive oil', '1 onion', '5 stalks celery', '1 cup mayo', '1 cup heavy cream'],
        'ingredients_subset': [],
        'directions': ['Prep: peel, cook, and chop pototoes. Chop onion and celery.', 'Mix everything together and season with salt and pepper. Chill and serve.'],
        'photo': '/static/images/potato-salad.jpg',
        'tags': ['Heather','Small Plate'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/potato-salad.jpg',
     },
     {
        'name': 'Tabouleh',
        'ingredients': ['3/4 cup bulgur', '1/4 cup lemon juice', '2 plum tomatoes', '1/4 cup fresh mint leaves', '1 scallion', '1/2 cup cucumber', '1/2 cup fresh parsley', '2 tbsp olive oil'],
        'ingredients_subset': [],
        'directions': ['Place bulgur in large bowl and add 1 cup boiling water and lemon juice, stir and cover in fridge for 30 min.', 'Dice tomatoes and cucumber. Thinly slice scallion. Chop mint and parsley.', 'Mix in rest of ingredients with bulgur, season with salt and pepper, and serve.'],
        'photo': '/static/images/tabouleh.jpg',
        'tags': ['Heather','Small Plate', 'Vegetarian'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/tabouleh.jpg',
     },
     {
        'name': 'Chicken & Broccoli Caserole',
        'ingredients': ['4-5 chicken breasts', '2-3 crowns broccoli', '1 can cream of chicken soup', '1 can crean of celery soup', '1/3 cup mayo', '1 tsp lemon juice', 'sage', 'thyme', 'paprika', '1/3 cup bread crumbs', '1/3 cup grated cheese', '2 1/2 tbsp butter'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 350 degrees F.', 'Make soup mixture: combine cream of chicken soup, cream of celery soup, mayo, lemon juice, sage, thyme, and paprika.', 'Grease casserole pan with butter. Pour in broccoli, then chicken, then soup mixture. Sprinkle with breadcrumbs and grated cheese. Dot with butter and bake for 30 min.'],
        'photo': '/static/images/chicken-and-broccoli.jpg',
        'tags': ['Heather','Entree'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/chicken-and-broccoli.jpg',
     },
     {
        'name': 'Kielbasa and Beans',
        'ingredients': ['2 pkg turkey kielbasa', '1/2 onion', '2 cans baked beans', '1 can dark red kidney beans', '1 can cannellini beans'],
        'ingredients_subset': ['1 cup brown sugar', '1 cup ketchup', '1/8 cup white vinegar', 'squirt of mustard', 'dash of Worcestershire', ],
        'directions': ['Preheat oven to 350 degrees F. Slice onion and kielbasa.', 'In saucepan, mix together 1 cup of water, sauce ingredients, and onion. Bring to a boil, then turn heat to low.', 'In large caserole, add kielbasa and beans, then mix in sauce. Bake for 1 hour, or 30 min if you heat beans on stovetop first.'],
        'photo': '/static/images/kielbasa-and-beans.jpg',
        'tags': ['Heather','Entree'],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/kielbasa-and-beans.jpg',
     },
     {
        'name': 'Losh Kebab',
        'ingredients': ['1 lb ground beef and/or lamb', '1/4 cup flour', '1/3 cup tomato paste', '1/3 cup onion', '1/3 tsp allspice', '1/3 tsp black pepper', '3 tsp salt', '2 tsp lemon juice', 'pita bread'],
        'ingredients_subset': [],
        'directions': ['Prep: chop onion, mix ingredients together, shape into kebabs. Grill or broil for 15 min, flipping halfway through.', 'Serve witih pita and jajek or greek salad.'],
        'photo': '/static/images/losh-kebab.jpg',
        'tags': ['Heather','Entree', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/losh-kebab.jpg',
     },
     {
        'name': 'Sweet & Sour Chicken',
        'ingredients': ['2 1/2 lb chicken', '3 tbsp butter', '1 egg', '1 cup baking mix', '1/3 cup brown sugar', '2 tbsp cornstarch', '1 can pineapple chunks', '3 tbsp vinegar', '3 tbsp ketchup', '3 tbsp soy sauce', '1 green bell pepper', '1 onion', 'rice'],
        'ingredients_subset': [],
        'directions': ['Preheat oven to 400 degrees F. Cook rice.', 'Prep: slice green pepper and onion. Drain pineapple and save syrup. Cut up chicken.', 'Beat egg with 2 tbsp water, dip chicken in then coat with baking mix or flour. Bake in greased pan until golden brown and done on each side, ~25-30 min for side 1 and ~10-15 min for side 2.', 'Mix brown sugar and conrstarch in saucepan. Add enough water to pineapple syrup to make 1 2/3 cups. Stir syrup mixture, vinegar, ketchup, and sauce sauce into saucepan. Cook over medium-high heat, stirring constantly, until thick and boiling.', 'Stir in pineapple, green pepper, and onion. Reuce heat.', 'Cover and simmer 5-7 min. Stir in chicken until hot, serve over rice.'],
        'photo': '/static/images/sweet-and-sour-chicken.jpg',
        'tags': ['Heather',],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/sweet-and-sour-chicken.jpg',
     },
     {
        'name': 'Chili',
        'ingredients': ['1 lb hamburger', '16 oz red beans', '16 oz white beans', '2 cloves garlic', '1/2 onion', '28 oz can crushed tomoatoes', '8 oz tomato sauce or 6 oz tomoato paste', '2 tsp thyme', '3 tsp cumin', '2 tbsp chili powder', '1/2 tsp basil', '1/2 tsp Worcestire sauce'],
        'ingredients_subset': ['Cornbread'],
        'directions': ['In large skillet, heat oil and saute garlic and onion. Brown meat. Add beans, tomoatoes, spices, and herbs.,', 'Bring to a boil, simmer 20 min until thick. Serve with cornbread.'],
        'photo': '/static/images/chili.jpg',
        'tags': ['Heather',],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/chili.jpg',
     },
     {
        'name': 'Sloppy Joes',
        'ingredients': ['1 1/2 lb ground beef', '1/4 cup onion', 'buns'],
        'ingredients_subset': ['1 tbsp brown sugar', '1 tsp mustard', '1 cup ketchup', '1/2 cup water', '2 tbsp vinegar', '2 tbsp Worcestshire'],
        'directions': ['Prep: chop onion.', 'Heat oil in large skillet, saute onion and brown meat.', 'Mix sauce ingredients and season with salt and pepper. Pour onto meat and simmer 30 min.'],
        'photo': '/static/images/sloppy-joes.jpg',
        'tags': ['Heather',],
        'formatted_tags': '',
        'source_name':'Mom\'s Recipe Book',
        'source': '/static/sources/sloppy-joes.jpg',
     },
     {
        'name': 'Jajek',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/jajek.jpg',
        'tags': ['Heather','Small Plate', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/jajek.jpg',
     },
     {
        'name': 'Dolma & Sarma',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/dolma.jpg',
        'tags': ['Heather','Entree', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/dolma.jpg',
     },
     {
        'name': 'Appetizer Sarma',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/sarma.jpg',
        'tags': ['Heather','Small Plate', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/sarma.jpg',
     },
     {
        'name': 'Keymali Ash',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/keymali-ash.jpg',
        'tags': ['Heather', 'Soup', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/keymali-ash.jpg',
     },
     {
        'name': 'Choreg',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/choreg.jpg',
        'tags': ['Heather', 'Small Plate', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/choreg.jpg',
     },
     {
        'name': 'Manti',
        'ingredients': [''],
        'ingredients_subset': [],
        'directions': [''],
        'photo': '/static/images/manti.jpg',
        'tags': ['Heather', 'Small Plate', 'Armenian'],
        'formatted_tags': '',
        'source_name':'Rose Baboian\'s Cook Book',
        'source': '/static/sources/manti.jpg',
     },
     # {
     #    'name': 'Placeholder',
     #    'ingredients': [''],
     #    'ingredients_subset': [],
     #    'directions': [''],
     #    'photo': '/static/images/placeholder.jpg',
     #    'tags': ['Heather', ],
     #    'formatted_tags': '',
     #    'source_name':'Mom\'s Recipe Book',
     #    'source': '/static/sources/placeholder.jpg',
     # },
	

]

def format_tags(): 
    for i in range(len(recipes)):
        recipes[i]['formatted_tags'] = " ".join(recipes[i]['tags'])

format_tags()

tag_list = []
all_tags = set(tag_list)

def master_tag_list():
    for i in range(len(recipes)):
        for tag in recipes[i]['tags']:
            all_tags.add(tag)

master_tag_list()



@app.route('/')
def home(): 
    return render_template('home.html', recipes = recipes)  

@app.route('/<recipe_name>')
def recipe(recipe_name):
    value = {}
    for recipe in recipes:
        if recipe['name'] == recipe_name:
            value = recipe
    return render_template('recipe.html', x=value)

if __name__ == '__main__':
    app.run(debug=True)
